package Windows;

import Others.CustomButton;
import Run.MyWindow;
import GameMechanics.GameMechanics;
import GameMechanics.Player;
import GameMechanics.Stock;
import Windows.JPanels.PaintLine;
import GameMechanics.Settings;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.LinkedList;

public class TradeWindow extends MyWindow {
    private final PaintLine paintLine;
    private final GameMechanics gameMechanics;
    private final LinkedList<Integer> yHistory;
    private final String shareName;
    private final JLabel playerMoney;
    private final JLabel stocksOwned;
    private final Player player;
    private final JLabel stockPrice;
    private final ArrayList<JButton> disabledButtons;
    private ArrayList<Integer> date;
    private Settings settings;

    public TradeWindow(GameMechanics gameMechanics, LinkedList<Integer> yHistoryInput, Player player, String shareName, ArrayList<Integer> date, Settings settings) {
        this.paintLine = new PaintLine();
        this.gameMechanics = gameMechanics;
        this.yHistory = yHistoryInput;
        this.player = player;
        this.shareName = shareName;
        this.playerMoney = new JLabel();
        this.stocksOwned = new JLabel();
        this.stockPrice = new JLabel();
        this.disabledButtons = new ArrayList<>();
        this.date = date;
        this.settings = settings;
    }

    public void init(ArrayList<Stock> stocks) {
        setTitle("Trade Window");
        setLayout(new BorderLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        add(paintLine, BorderLayout.CENTER);

        northComponentsInit(stocks);
        southComponentsInit();

        //generated by AI from 57-64
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escapePressed");
        getRootPane().getActionMap().put("escapePressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new MainWindow(gameMechanics, stocks, player, date, settings).init();
            }
        });

        setVisible(true);

        paintLine.paint(yHistory, date, gameMechanics);
        updateText();
    }

    @Override
    public void update() {
        gameMechanics.addNextNumber();
        date = gameMechanics.updateDate(date);
        paintLine.paint(yHistory, date, gameMechanics);
        updateText();
    }

    public void updateText() {
        playerMoney.setText("Money: " + player.getMoneyText(settings.getCurrency()));
        stocksOwned.setText("Owned: " + player.getAmountOfStocksOwned(shareName));
        stockPrice.setText(yHistory.getLast() + " " + settings.getCurrency());
    }

    public void southComponentsInit() {
        JPanel southPanel = new JPanel();

        JButton buyMax = new JButton("Buy Max");
        CustomButton.changeLightGray35(buyMax);
        southPanel.add(buyMax);

        JButton buy5x = new JButton("Buy 5x");
        CustomButton.changeLightGray35(buy5x);
        southPanel.add(buy5x);

        JButton buyButton = new JButton("Buy");
        CustomButton.changeLightGray35(buyButton);
        southPanel.add(buyButton);


        JButton sellButton = new JButton("Sell");
        CustomButton.changeLightGray35(sellButton);
        southPanel.add(sellButton);

        JButton sell5x = new JButton("Sell 5x");
        CustomButton.changeLightGray35(sell5x);
        southPanel.add(sell5x);

        JButton sellMax = new JButton("Sell Max");
        CustomButton.changeLightGray35(sellMax);
        southPanel.add(sellMax);

        add(southPanel, BorderLayout.SOUTH);

        disabledButtons.add(buyMax);
        disabledButtons.add(buy5x);
        disabledButtons.add(buyButton);
        disabledButtons.add(sellButton);
        disabledButtons.add(sell5x);
        disabledButtons.add(sellMax);

        buyMax.addActionListener(e -> {
            gameMechanics.buyStock(shareName, yHistory.getLast(), player.getMoney() / yHistory.getLast());
            updateText();
        });

        buy5x.addActionListener(e -> {
            gameMechanics.buyStock(shareName, yHistory.getLast(), 5);
            updateText();
        });

        buyButton.addActionListener(e -> {
            new BuyDialog(this, gameMechanics, player, shareName, yHistory.getLast(), settings);
            updateText();
        });

        sellButton.addActionListener(e -> {
            new SellDialog(this, gameMechanics, player, shareName, yHistory.getLast(), settings);
            updateText();
        });

        sell5x.addActionListener(e -> {
            gameMechanics.sellStock(shareName, yHistory.getLast(), 5);
            updateText();
        });

        sellMax.addActionListener(e -> {
            gameMechanics.sellStock(shareName, yHistory.getLast(), player.getAmountOfStocksOwned(shareName));
            updateText();
        });
    }

    public void northComponentsInit(ArrayList<Stock> stocks) {
        JPanel northPanel = new JPanel(new BorderLayout());

        JButton buttonBack = new JButton("←");
        CustomButton.changeRed(buttonBack);
        JPanel leftPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        leftPanel.add(buttonBack);

        JButton buttonNextweek = new JButton("Next Week");
        CustomButton.changeGreen(buttonNextweek);
        JPanel rightPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        rightPanel.add(buttonNextweek);

        JPanel gridPanel = new JPanel(new GridLayout(1, 5));
        gridPanel.add(leftPanel);

        playerMoney.setFont(new Font("Times New Roman", Font.PLAIN, 30));
        JPanel leftCenterPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 13));
        leftCenterPanel.add(playerMoney);
        gridPanel.add(leftCenterPanel);

        JPanel namePriceStock = new JPanel(new GridLayout(2, 1));
        JLabel labelShareName = new JLabel(shareName, SwingConstants.CENTER);
        labelShareName.setFont(new Font("Times New Roman", Font.BOLD, 35));
        namePriceStock.add(labelShareName);

        stockPrice.setFont(new Font("Times New Roman", Font.PLAIN, 25));
        stockPrice.setHorizontalAlignment(SwingConstants.CENTER);
        namePriceStock.add(stockPrice);

        gridPanel.add(namePriceStock);

        stocksOwned.setFont(new Font("Times New Roman", Font.PLAIN, 30));
        JPanel rightCenterPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 13));
        rightCenterPanel.add(stocksOwned);
        gridPanel.add(rightCenterPanel);

        gridPanel.add(rightPanel);
        northPanel.add(gridPanel, BorderLayout.CENTER);
        add(northPanel, BorderLayout.NORTH);

        disabledButtons.add(buttonNextweek);
        disabledButtons.add(buttonBack);

        buttonNextweek.addActionListener(e -> run(disabledButtons, settings));

        buttonBack.addActionListener(e -> {
            dispose();
            new MainWindow(gameMechanics, stocks, player, date, settings).init();
        });
    }
}
